### PR TITLE
Support for directory backups

### PR DESCRIPTION
**Pull request by rohitkrai03**
Added a new feature to support directory backups.

While adding this feature I adhered to same conventions used in other db backups.
I think it might be useful to others as it is to us. We use it in production.

### CODE REVIEW

**Comment by epicserve** [comment]
Do you have any thoughts or suggestions on how we could write a test to test this script?

**Comment by epicserve** [comment]
When building the docs I get:

```
/Users/brento/Code/s3-backups/docs/index.rst:57: WARNING: Title underline too short.

Directory
'''''
```

Also after rebasing your changes against master and running tests I get:

```
make test
Checking code using pep8 ...
Checking code using pyflakes ...
./s3_backups/dir_to_s3.py:12: 'subprocess' imported but unused
./s3_backups/dir_to_s3.py:61: undefined name 't2'
make: [test] Error 1 (ignored)
Running tests ...
...
----------------------------------------------------------------------
Ran 3 tests in 0.005s
```

**Comment by rohitkrai03** [comment]
I've made some changes according to your above tests. Now, i think it should pass all the tests.

And about testing the script we could write a test which will after running the script check the s3 bucket if the directory is uploaded successfully or not.

**Comment by epicserve** [comment]
If I can ever find time I would like to test things the way [boto does](https://github.com/boto/boto/tree/develop/tests/unit/s3) by using mock.

Also, what is the advantage of having something like dir_to_s3 in s3-backup when there are tools like [s3cmd sync](http://s3tools.org/s3cmd-sync) and [boto rsync](https://pypi.python.org/pypi/boto_rsync/0.8.1)?

**Comment by rohitkrai03** [comment]
s3cmd sync seems good. But the only thing is we were using s3-backups for postgres and redis in our production server already and needed something for directories also which can be easily handled by fabric.

**Comment by epicserve** [comment]
You can run any linux command you want with fabric (e.g. ``run('s3cmd put --recursive dir1 s3://s3tools-demo/some/path/')``), so I don't see why you could just s3cmd sync or boto rsync ... am I missing something?

**Comment by rohitkrai03** [comment]
Yeah, i know that i can run any command with fabric. the thing is i was not aware that s3cmd had a sync utility which could make my life easier. So, i kind of reinvented the wheel. As of now, we're using dir_to_s3 for backups but thinking of switching to s3cmd rsync in future.

**Comment by epicserve** [comment]
Okay, sounds good. I think I'm just going to close this PR without pulling it in because to be honest I don't really want to support it if there are already solutions available. Thank you for your contribution. If I end up getting a lot of requests for this type of feature in the future, it might be worth exploring the idea of including it in s3-backups.

**Pull request closed without merging**
